---
title: "EDLD 610 Spring 2020 Final Project Outline"
author: "Claire Zhang; JP Pedroza; Thuy Nguyen; Jim Wright"
date: "4/16/2020"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: "spacelab"
    highlight: "tango"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)

safe <- import(here("data", "2006_school_safety.sav"),
               setclass = "tbl_df") %>% 
  characterize() %>% 
  janitor::clean_names() 

safe06 <- import(here("data", "2006_school_safety_v2.sav"),
               setclass = "tbl_df") %>% 
  characterize() %>% 
  janitor::clean_names() 

safe08 <- import(here('data', '2008_school_safety.sav'),
                 setclass = 'tbl_df') %>% 
  characterize() %>% 
  janitor::clean_names()
```

### Chosen Format
For our final project, we intend to use a shiny application. 


### Purpose 
The purpose of our final project will be substantive and include a final product that could be utilized by a client, such as an educational agency. 


### Description of the Data 
The data for our project comes from the 2005-2006 School Survey on Crime and Safety. The data was obtained via [data.gov](https://catalog.data.gov/dataset/2006-school-survey-on-crime-and-safety) and is a large SPSS file with 2,724 rows by 525 columns. The goal of our project will be to explore the relation between various variables within the data set. Specifically, four categorical variables we intend to use in models include: _school enrollment_, _minority percentage school enrollment_, _school urbanicity_, _school level_. These variables will be modeled to predict the following quantitative outcome variable: _out of school suspensions_. Further, we will explore the relation between the provision of teacher training on predicting out of school suspensions as well as the relation between the aforementioned categorical variables on predicting the provision of teacher training. The teacher training variables are logical with a binary yes/no coded response. We intend for our final product to identify trends that would be helpful for school administrations to identify what types of teacher trainings may prevent out of school suspensions. 


### Lingering Questions

# JP's note:
Hey all, while I was looking into the SSOCS data, the main data source is at [The National Center for Education Statistics](https://nces.ed.gov/surveys/ssocs/index.asp). I found that the data in this file has a similar file for the following cycle (07-08). I thought since we are in interested in a shiny app, which includes dropdown menus to show differences, we could have a dropdown menu that shows our models between the year cycles. This is just a thought and it wouldn't add much to our work but would add more to the implications of the app. 