---
title: "Jim Preliminary Work"
author: "Jim Wright"
date: "5/7/2020"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: "spacelab"
    highlight: "tango"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rio)
library(here)
library(tidyverse)
library(gt)

safe06 <- import(here("spss_files", "2006_school_safety.sav"),
               setclass = "tbl_df") %>% 
  characterize() %>% 
  janitor::clean_names() 

safe08 <- import(here('spss_files', '2008_school_safety.sav'),
                 setclass = 'tbl_df') %>% 
  characterize() %>% 
  janitor::clean_names()

safe18 <- import(here('spss_files', '2018_school_safety.sav'),
                 setclass = 'tbl_df') %>% 
  characterize() %>% 
  janitor::clean_names()

all_safe <- bind_rows("05-06 Survey" = safe06, 
                      "07-08 Survey" = safe08, 
                      "17-18 Survey" = safe18, 
                      .id = "dataset")

head(all_safe)
```


### School Totals
```{r descriptive statistics, include=FALSE}
school_minority <- all_safe %>% 
  select(dataset, schid, fr_catmn, fr_lvel, fr_urban, fr_size) %>% 
  group_by(dataset, fr_catmn) %>% 
  summarize(n=n()) %>% 
  na.omit() %>% 
  gt() %>% 
  cols_label(fr_catmn = "Minority Status",
             n = "Total") %>% 
  cols_align(align = "left", columns = vars(fr_catmn)) %>% 
  cols_align(align = "center", columns = vars(n)) %>% 
  tab_header(title = "Number of Schools by Minority Status")

school_minority

school_size <- all_safe %>% 
  select(dataset, schid, fr_catmn, fr_lvel, fr_urban, fr_size) %>% 
  group_by(dataset, fr_size) %>% 
  summarize(n=n()) %>% 
  na.omit() %>% 
  gt() %>% 
  cols_label(fr_size = "Enrollment",
             n = "Total") %>% 
  cols_align(align = "left", columns = vars(fr_size)) %>% 
  cols_align(align = "center", columns = vars(n)) %>% 
  tab_header(title = "Number of Schools by Size")

school_size

school_level <- all_safe %>% 
  select(dataset, schid, fr_catmn, fr_lvel, fr_urban, fr_size) %>% 
  group_by(dataset, fr_lvel) %>% 
  summarize(n=n()) %>% 
  na.omit() %>% 
  gt() %>% 
  cols_label(fr_lvel = "School Level",
             n = "Total") %>% 
  cols_align(align = "left", columns = vars(fr_lvel)) %>% 
  cols_align(align = "center", columns = vars(n)) %>% 
  tab_header(title = "Number of Schools by Level")

school_level


school_urban <- all_safe %>% 
  select(dataset, schid, fr_catmn, fr_lvel, fr_urban, fr_size) %>% 
  group_by(dataset, fr_urban) %>% 
  summarize(n=n()) %>% 
  na.omit() %>% 
  gt() %>% 
  cols_label(fr_urban = "Urbanicity",
             n = "Total") %>% 
  cols_align(align = "left", columns = vars(fr_urban)) %>% 
  cols_align(align = "center", columns = vars(n)) %>% 
  tab_header(title = "Number of Schools by Urbanicity")

school_urban
```

### Descriptive Statistics Tables
```{r tables, include=TRUE}
school_level

school_minority

school_size

school_urban
```

### What is the relationship between school urbanicity and the percentage of students likely to go to college across each year of the survey?
```{r}
by_year <- split(all_safe, all_safe$dataset)


mods <- map(by_year, ~lm(c0534 ~ fr_urban, data = .x))

str(mods)

coefs <- map(mods, coef) 

coefs[c(1:2, length(coefs))]

slopes <- map_dbl(coefs, 2)

slopes
```


### Function Practice 
```{r}
d <- all_safe %>% 
  select(dataset, schid, c0508, c0510, c0514, outsus06, outsus08, outsus18, c0534, c0536, c0568, c0178, c0180, c0181, c0182, c0192, c0194, c0196, c0198, c0200, c0202, c0175, c0179, c0186, fr_catmn, fr_lvel, fr_urban, fr_size)

names(d)
head(d)

my_mean <- function(x) {
  z <- na.omit(x)
  sum(z) / length(z)
}

mean_insubordination <- my_mean(d$c0508)

mean(d$c0508, na.rm = TRUE)


level_proportion <- function(x) {
  map_dbl(split(x, x), length) / length(x)
}

insubordination_suspension_proportion <- level_proportion(d$c0514)

z_distribution <- function(x) {
  (x - mean(x, na.rm = TRUE)) / 
  sd(x, na.rm = TRUE) 
}

z_dstr_oss06 <- z_distribution(d$outsus06)

d_tidy_outsus <- d %>% 
  pivot_longer(
    cols = c(outsus06, outsus08, outsus18),
    names_to = "suspensions",
    values_to = "outsus"
  )

suspension_size <- d_tidy_outsus %>% 
  group_by(dataset, schid, outsus, fr_size) %>% 
  nest()

size_model <- function(df) {
  lm(outsus ~ fr_size, data = df)
}

suspension_size <- suspension_size %>% 
  mutate(model = map(data, size_model))

#couldn't get this to run properly because outsus column couldn't be identified 


# percentage of students likely to go to college - c0534

college_size <- d %>% 
  group_by(dataset, schid, c0534, fr_size) %>% 
  nest()

size_college_model <- function(df) {
  lm(c0534 ~ fr_size, data = df)
}

college_size <- college_size %>% 
  mutate(model = map(data, size_college_model))
```


